### ISSUE TITLE
COM4 board not available

### ISSUE THREAD

**Issue by CLGamesStudio** [Xinyuan-LilyGO/TTGO-T-Display#107]
Help me please! I flashed the board several times, but after loading the Tetris game on it, it stopped being displayed on the device panel, when the PC board is connected, it sees it, but when I try to load a new program, the com port disappears from the list. Thank you in advance
P.S. type-c cable is ok

**Comment by lewisxhe** [comment]
It may be poor contact If you have hands-on ability, try to weld the TYPE-C seat
