### ISSUE TITLE
Reintroduce the MIT Licence

### ISSUE THREAD

**Issue by kreier** [Xinyuan-LilyGO/TTGO-T-Display#108]
With issue 13 https://github.com/Xinyuan-LilyGO/TTGO-T-Display/issues/13 the MIT license was added on January 6th, 2020 by @lewisxhe . Unfortunately with the merge of April 14th, 2020 https://github.com/Xinyuan-LilyGO/TTGO-T-Display/commit/7d9561e308fdc78e134ba8f0ee3158ec77653db2 by Lewis He (see history https://github.githistory.xyz/Xinyuan-LilyGO/TTGO-T-Display/blob/master/LICENSE) the license was deleted.

**Comment by lewisxhe** [comment]
Sorry, it has been added again
