### ISSUE TITLE
Tiny mistake on pinout picture

### ISSUE THREAD

**Issue by estevaofv** [Xinyuan-LilyGO/TTGO-T-Display#2]
Hello, I was checking the pinout diagram and I think I found a mistake. Instead of GPIO14  (in purple) it should be GPIO 13

![image](https://user-images.githubusercontent.com/12235551/61977589-3854a400-afc5-11e9-8be7-ea701fc3d520.png)

just like in the schematics:

![image](https://user-images.githubusercontent.com/12235551/61977637-5a4e2680-afc5-11e9-9150-b241c875fd11.png)

**Comment by lewisxhe** [comment]
Thank you for your reminder, I will give feedback

**Comment by LilyGO** [comment]
Changes are complete
