### ISSUE TITLE
Rx/Tx pins ?

### ISSUE THREAD

**Issue by JoeBarouneD** [Xinyuan-LilyGO/TTGO-T-Display#25]
Hello, i bought this module to have "versatility" with his screen and buttons.

I have not yet an USB-C cable and i wanted to begin programming the board.

Is there a way to program it, without pluging it with USB (other ESP32 can be flashed by Rx/Tx pins, for exemple) ?

Thanks !

**Comment by dmiart** [comment]
All hardware serial pins seems to be connected already, so they are not accessibly externally. UART0 seems to be used by USB port, UART1 by serial flash memory and UART2 pins I think is connected to the LCD screen.

**Comment by JoeBarouneD** [comment]
Yes i think i can close this ticket.
