### ISSUE TITLE
Polarity of LiPo battery connector

### ISSUE THREAD

**Issue by levycarneiro** [Xinyuan-LilyGO/TTGO-T-Display#82]
Hello all!

The board doesn't have the usual + and - markings near the battery connector, and I don't want to fry the board :)

Does anyone know which one is + and - ?

Thanks.

**Comment by levycarneiro** [comment]
Realized that the pigtail cable that comes with the board already has the needed polarity.

**Comment by MrMcChip** [comment]
The appropriate and usually supplied connector is polarized and thus only
plugs in one way. It can be verified without power using an ohm meter. And
then using the appropriate black and red sharpie markers for future
reference
