### ISSUE TITLE
How to power the  TTGO-T-Display without using USB 

### ISSUE THREAD

**Issue by nielsnl68** [Xinyuan-LilyGO/TTGO-T-Display#99]
Hi, 

I would love to use the [TTGO-T-Display](https://github.com/Xinyuan-LilyGO/TTGO-T-Display) without having the usb and battery connected.

I tried to put 5 volt on the 5v pin but that did not work for me. Is there an other solution that i'm missing?

**Comment by sangngocle** [comment]
If the 5V pin does not work, you should try the battery port, To make sure 5V won't burn the regulator, you should try to put 4.2V into it first.
